import css from 'styled-jsx/css'


export default css`


                .scale-up-center {
                    -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
                    animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
                }


                .scale-up-top {
                    -webkit-animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
                    animation: scale-up-top 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
                }

                .fade-in {
	                -webkit-animation: fade-in 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	                animation: fade-in 2s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
                }

                /* ----------------------------------------------
                * Generated by Animista on 2020-5-20 17:30:12
                * Licensed under FreeBSD License.
                * See http://animista.net/license for more info.
                * w: http://animista.net, t: @cssanimista
                * ---------------------------------------------- */

                /**
                 * ----------------------------------------
                 * animation scale-up-top
                 * ----------------------------------------
                 */
                @-webkit-keyframes scale-up-top {
                0% {
                    -webkit-transform: scale(0.5);
                            transform: scale(0.5);
                    -webkit-transform-origin: 50% 0%;
                            transform-origin: 50% 0%;
                }
                100% {
                    -webkit-transform: scale(1);
                            transform: scale(1);
                    -webkit-transform-origin: 50% 0%;
                            transform-origin: 50% 0%;
                }
                }
                @keyframes scale-up-top {
                0% {
                    -webkit-transform: scale(0.5);
                            transform: scale(0.5);
                    -webkit-transform-origin: 50% 0%;
                            transform-origin: 50% 0%;
                }
                100% {
                    -webkit-transform: scale(1);
                            transform: scale(1);
                    -webkit-transform-origin: 50% 0%;
                            transform-origin: 50% 0%;
                }
                }


                /* ----------------------------------------------
                * Generated by Animista on 2020-5-20 18:11:40
                * Licensed under FreeBSD License.
                * See http://animista.net/license for more info.
                * w: http://animista.net, t: @cssanimista
                * ---------------------------------------------- */

                /**
                 * ----------------------------------------
                 * animation fade-in
                 * ----------------------------------------
                 */
                @-webkit-keyframes fade-in {
                0% {
                    opacity: 0;
                }
                100% {
                    opacity: 1;
                }
                }
                @keyframes fade-in {
                0% {
                    opacity: 0;
                }
                100% {
                    opacity: 1;
                }
                }

                /* ----------------------------------------------
                    * Generated by Animista on 2020-5-20 20:30:57
                    * Licensed under FreeBSD License.
                    * See http://animista.net/license for more info.
                    * w: http://animista.net, t: @cssanimista
                    * ---------------------------------------------- */

                    /**
                     * ----------------------------------------
                     * animation scale-up-center
                     * ----------------------------------------
                     */
                    @-webkit-keyframes scale-up-center {
                    0% {
                        -webkit-transform: scale(0.5);
                                transform: scale(0.5);
                    }
                    100% {
                        -webkit-transform: scale(1);
                                transform: scale(1);
                    }
                    }
                    @keyframes scale-up-center {
                    0% {
                        -webkit-transform: scale(0.5);
                                transform: scale(0.5);
                    }
                    100% {
                        -webkit-transform: scale(1);
                                transform: scale(1);
                    }
                    }



`